/********************************************************************
* pollackProjectDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error pollackProjectDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablepollackProjectDict();
extern void G__cpp_setup_inheritancepollackProjectDict();
extern void G__cpp_setup_typetablepollackProjectDict();
extern void G__cpp_setup_memvarpollackProjectDict();
extern void G__cpp_setup_globalpollackProjectDict();
extern void G__cpp_setup_memfuncpollackProjectDict();
extern void G__cpp_setup_funcpollackProjectDict();
extern void G__set_cpp_environmentpollackProjectDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "pollackProjectHeaders.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__pollackProjectDictLN_TClass;
extern G__linked_taginfo G__pollackProjectDictLN_TBuffer;
extern G__linked_taginfo G__pollackProjectDictLN_TMemberInspector;
extern G__linked_taginfo G__pollackProjectDictLN_TObject;
extern G__linked_taginfo G__pollackProjectDictLN_string;
extern G__linked_taginfo G__pollackProjectDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__pollackProjectDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pollackProjectDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__pollackProjectDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pollackProjectDictLN_TCMET;
extern G__linked_taginfo G__pollackProjectDictLN_TVector2;
extern G__linked_taginfo G__pollackProjectDictLN_TCJet;
extern G__linked_taginfo G__pollackProjectDictLN_TCPhysObject;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__pollackProjectDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__pollackProjectDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_TVector3;
extern G__linked_taginfo G__pollackProjectDictLN_TLorentzVector;
extern G__linked_taginfo G__pollackProjectDictLN_pairlEstringcOfloatgR;
extern G__linked_taginfo G__pollackProjectDictLN_vectorlEpairlEstringcOfloatgRcOallocatorlEpairlEstringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__pollackProjectDictLN_reverse_iteratorlEvectorlEpairlEstringcOfloatgRcOallocatorlEpairlEstringcOfloatgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pollackProjectDictLN_TCElectron;
extern G__linked_taginfo G__pollackProjectDictLN_TCMuon;
extern G__linked_taginfo G__pollackProjectDictLN_TCPhoton;
extern G__linked_taginfo G__pollackProjectDictLN_TCPhotoncLcLCrystalInfo;
extern G__linked_taginfo G__pollackProjectDictLN_TCTriggerObject;
extern G__linked_taginfo G__pollackProjectDictLN_TCGenJet;
extern G__linked_taginfo G__pollackProjectDictLN_TCGenParticle;
extern G__linked_taginfo G__pollackProjectDictLN_TCPrimaryVtx;

/* STUB derived class for protected member access */
