//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCElectron_h
#define TCElectron_h
class TCElectron;

#include "TCPhysObject.h"
#include "TLorentzVector.h"

class TCElectron : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       _ptError;    //
   float       _hadOverEm;    //
   float       _dPhiSuperCluster;    //
   float       _dEtaSuperCluster;    //
   float       _sigmaIetaIeta;       //
   float       _eOverP;              //
   float       _fBrem;               //
   float       _r9;                  //
   float       _scEta;               //
   bool        _convVeto;            //
   short       _convMissHits;        //
   bool        _isEB;                //true if particle is in ECAL Barrel
   bool        _isEE;                //true if particle is in ECAL Endcaps
   bool        _isInGap;             //
   float       _normalizedChi2;      //
   int         _numberOfValidPixelHits;    //
   int         _numberOfValidTrackerHits;    //
   int         _numberOfLostPixelHits;       //
   int         _numberOfLostTrackerHits;     //
   int         _cut95;                       //
   int         _cut90;                       //
   int         _cut85;                       //
   int         _cut80;                       //
   int         _cut70;                       //
   int         _cut60;                       //
   TLorentzVector _regressionMomCombP4;         //

   TCElectron();
   TCElectron(const TCElectron & );
   virtual ~TCElectron();

   ClassDef(TCElectron,2); // Generated by MakeProject.
};
#endif
