//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCGenParticle_h
#define TCGenParticle_h
class TCGenParticle;

#include "TCPhysObject.h"

class TCGenParticle : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         mother;      //
   int         grandmother;    //
   int         PDGID;          //
   unsigned int status;         //
   bool         isParton_;      //

   TCGenParticle();
   TCGenParticle(const TCGenParticle & );
   virtual ~TCGenParticle();

   ClassDef(TCGenParticle,2); // Generated by MakeProject.
};
#endif
