//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCGenJet_h
#define TCGenJet_h
class TCGenJet;

#include "TCPhysObject.h"
#include "TLorentzVector.h"

class TCGenJet : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector _progenitorP4;    //
   float          _hadEnergy;       //
   float          _emEnergy;        //
   float          _invEnergy;       //
   float          _auxEnergy;       //
   unsigned int   _numConstit;      //
   unsigned int   _numChPart;       //
   int            _jetFlavor;       //

   TCGenJet();
   TCGenJet(const TCGenJet & );
   virtual ~TCGenJet();

   ClassDef(TCGenJet,2); // Generated by MakeProject.
};
#endif
