//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCJet_h
#define TCJet_h
class TCJet;

#include "TCPhysObject.h"
#include "Riostream.h"
#include <map>

class TCJet : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       _vtxSumPtFrac;    //
   float       _vtxSumPt;        //
   float       _vtxTrackFrac;    //
   float       _vtxNTracks;      //
   unsigned int _vtxSumPtIndex;    //
   unsigned int _vtxCountIndex;    //
   float        _jesUncertainty;    //
   float        _chHadFrac;         //
   float        _neuHadFrac;        //
   float        _chEmFrac;          //
   float        _neuEmFrac;         //
   unsigned int _numConstit;        //
   unsigned int _numChPart;         //
   std::vector<std::pair<std::string,float> > _bDiscrMap;         //
   int                                        _jetFlavor;         //

   TCJet();
   TCJet(const TCJet & );
   virtual ~TCJet();

   ClassDef(TCJet,2); // Generated by MakeProject.
};
#endif
