//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCMuon_h
#define TCMuon_h
class TCMuon;

#include "TCPhysObject.h"

class TCMuon : public TCPhysObject {

public:
// Nested classes declaration.

public:
// Data Members.
   float       _ptError;    //
   bool        _isPF;       //
   bool        _isTRK;      //
   bool        _isGLB;      //
   float       _caloComp;    //
   float       _segComp;     //
   int         _numberOfMatches;    //
   int         _numberOfMatchedStations;    //
   int         _numberOfValidPixelHits;     //
   int         _numberOfValidTrackerHits;    //
   int         _numberOfLostPixelHits;       //
   int         _numberOfLostTrackerHits;     //
   int         _numberOfValidMuonHits;       //
   int         _trackLayersWithMeasurement;    //
   float       _normalizedChi2;                //

   TCMuon();
   TCMuon(const TCMuon & );
   virtual ~TCMuon();

   ClassDef(TCMuon,2); // Generated by MakeProject.
};
#endif
