//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCPhysObject_h
#define TCPhysObject_h
class TCPhysObject;

#include "TLorentzVector.h"
#include "TVector3.h"
#include "Riostream.h"
#include <map>
#include <string>

class TCPhysObject : public TLorentzVector {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    _vtx;        //
   std::vector<std::pair<std::string,float> > _IdMap;      //
   std::vector<std::pair<std::string,float> > _IsoMap;     //
   int                                        _charge;     //
   string                                     _type;       //
   bool                                       _isPF;       //
   bool                                       _isReco;     //

   TCPhysObject();
   TCPhysObject(const TCPhysObject & );
   virtual ~TCPhysObject();

   ClassDef(TCPhysObject,2); // Generated by MakeProject.
};
#endif
