//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Sep  2 09:05:57 2013 by ROOT version 5.32/00)
//      from the StreamerInfo in file nuTuple.root
//////////////////////////////////////////////////////////


#ifndef TCTriggerObject_h
#define TCTriggerObject_h
class TCTriggerObject;

#include "TLorentzVector.h"
#include "Riostream.h"
#include <string>

class TCTriggerObject : public TLorentzVector {

public:
// Nested classes declaration.

public:
// Data Members.
   int         _id;         //
   string      _HLTName;    //
   string      _moduleName;    //

   TCTriggerObject();
   TCTriggerObject(const TCTriggerObject & );
   virtual ~TCTriggerObject();

   ClassDef(TCTriggerObject,2); // Generated by MakeProject.
};
#endif
